/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg:              "#f1f1f1",
        surface:         "#f1f1f1",
        "surface-raised":"#ffffff",
        border:          "#e0e0e0",
        "border-strong": "#0063DA",
        accent:          "#0063DA",
        "on-accent":     "#f1f1f1",
        "accent-dark":   "#004eb1",
        "accent-dim":    "#e6f0ff",
        secondary:       "#0063DA",
        "on-secondary":  "#f1f1f1",
        "secondary-dim": "#e6f0ff",
        text:            "#111111",
        "text-muted":    "#555555",
        "text-dim":      "#777777",
      },
      borderRadius: {
        none:    "0",
        DEFAULT: "0",
        sm:      "0",
        md:      "0",
        lg:      "0",
        xl:      "0",
        "2xl":   "0",
        "3xl":   "0",
        full:    "0",
      },
      spacing: {
        gutter:                    "24px",
        "section-padding-desktop": "120px",
        "section-padding-mobile":  "64px",
        base:                      "8px",
        "container-max":           "1280px",
      },
      fontFamily: {
        display: ["Barlow Condensed", "sans-serif"],
        mono:    ["JetBrains Mono", "monospace"],
        body:    ["Barlow", "sans-serif"],
      },
      fontSize: {
        "hero":        ["88px", { lineHeight: "0.95", letterSpacing: "-0.01em", fontWeight: "900" }],
        "hero-mobile": ["48px", { lineHeight: "1.0",  letterSpacing: "-0.01em", fontWeight: "900" }],
        "h1":          ["64px", { lineHeight: "1.0",  letterSpacing: "-0.01em", fontWeight: "800" }],
        "h1-mobile":   ["36px", { lineHeight: "1.1",  letterSpacing: "0",       fontWeight: "800" }],
        "h2":          ["48px", { lineHeight: "1.05", letterSpacing: "0",       fontWeight: "700" }],
        "h2-mobile":   ["30px", { lineHeight: "1.1",  fontWeight: "700" }],
        "h3":          ["28px", { lineHeight: "1.2",  fontWeight: "700" }],
        "body-lg":     ["18px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "1.65", fontWeight: "400" }],
        "mono-sm":     ["13px", { lineHeight: "1",    letterSpacing: "0.08em", fontWeight: "700" }],
        "mono-xs":     ["11px", { lineHeight: "1",    letterSpacing: "0.1em",  fontWeight: "700" }],
      },
      transitionTimingFunction: {
        "out-fast":  "cubic-bezier(0.16, 1, 0.3, 1)",
        "out-sharp": "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      transitionDuration: {
        "150": "150ms",
        "250": "250ms",
      },
      boxShadow: {
        "hard-accent":    "4px 4px 0 #0063DA",
        "hard-accent-lg": "6px 6px 0 #0063DA",
        "hard-border":    "4px 4px 0 #111111",
        "hard-secondary": "4px 4px 0 #0063DA",
        "hard-black":     "4px 4px 0 #111111",
        none:             "none",
      },
    },
  },
};
