/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg:              "#0A0A0A",
        surface:         "#111111",
        "surface-raised":"#191919",
        border:          "#2A2A2A",
        "border-strong": "#3D3D3D",
        accent:          "#AAFF00",
        "on-accent":     "#0A0A0A",
        "accent-dark":   "#88CC00",
        "accent-dim":    "#1A2600",
        secondary:       "#FF3C00",
        "on-secondary":  "#0A0A0A",
        "secondary-dim": "#1F0900",
        text:            "#F0F0F0",
        "text-muted":    "#888888",
        "text-dim":      "#555555",
      },
      borderRadius: {
        none:    "0",
        DEFAULT: "0",
        sm:      "0",
        md:      "0",
        lg:      "0",
        xl:      "0",
        "2xl":   "0",
        "3xl":   "0",
        full:    "0",
      },
      spacing: {
        gutter:                    "24px",
        "section-padding-desktop": "120px",
        "section-padding-mobile":  "64px",
        base:                      "8px",
        "container-max":           "1280px",
      },
      fontFamily: {
        display: ["Barlow Condensed", "sans-serif"],
        mono:    ["JetBrains Mono", "monospace"],
        body:    ["Barlow", "sans-serif"],
      },
      fontSize: {
        "hero":        ["88px", { lineHeight: "0.95", letterSpacing: "-0.01em", fontWeight: "900" }],
        "hero-mobile": ["48px", { lineHeight: "1.0",  letterSpacing: "-0.01em", fontWeight: "900" }],
        "h1":          ["64px", { lineHeight: "1.0",  letterSpacing: "-0.01em", fontWeight: "800" }],
        "h1-mobile":   ["36px", { lineHeight: "1.1",  letterSpacing: "0",       fontWeight: "800" }],
        "h2":          ["48px", { lineHeight: "1.05", letterSpacing: "0",       fontWeight: "700" }],
        "h2-mobile":   ["30px", { lineHeight: "1.1",  fontWeight: "700" }],
        "h3":          ["28px", { lineHeight: "1.2",  fontWeight: "700" }],
        "body-lg":     ["18px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "1.65", fontWeight: "400" }],
        "mono-sm":     ["13px", { lineHeight: "1",    letterSpacing: "0.08em", fontWeight: "700" }],
        "mono-xs":     ["11px", { lineHeight: "1",    letterSpacing: "0.1em",  fontWeight: "700" }],
      },
      transitionTimingFunction: {
        "out-fast":  "cubic-bezier(0.16, 1, 0.3, 1)",
        "out-sharp": "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      transitionDuration: {
        "150": "150ms",
        "250": "250ms",
      },
      boxShadow: {
        "hard-accent":    "4px 4px 0 #AAFF00",
        "hard-accent-lg": "6px 6px 0 #AAFF00",
        "hard-border":    "4px 4px 0 #3D3D3D",
        "hard-secondary": "4px 4px 0 #FF3C00",
        "hard-black":     "4px 4px 0 #0A0A0A",
        none:             "none",
      },
    },
  },
};
